version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 180
      runas: root

  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 180
      runas: root