version: 0.0
os: linux

files:
  - source: ./build/libs/ROOT.war
    destination: /var/lib/tomcat7/webapps

hooks:
  AfterInstall:
   - location: ./AfterInstall.sh
     timeout: 180
     runas: centos

    Application Start:
  - location: ./ApplicationStart.sh
    timeout: 180
    runas: centos

    Application Stop:
  - location: ./ApplicationStop.sh
    timeout: 180
    runas: centos