version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu

hooks:
  AfterInstall:
   - location: scripts/AfterInstall.sh
     timeout: 180
     runas: centos

    Application Start:
  - location: scripts/ApplicationStart.sh
    timeout: 180
    runas: centos

    Application Stop:
  - location: scripts/ApplicationStop.sh
    timeout: 180
    runas: centos