name: Node.js CI

on: 
  pull_request: 
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
          node-version: '14.x'

    - name: build 
      run: |
            ls
            npm install

    - name: test
      run: |
          npm install pm2 -g
          pm2 start --name testServer npm -- test
          pm2 stop testServer

    - name: Build Artifacts
      run: |
          ls -al
          cd ~/
          sudo apt install wget zip unzip curl -y
          sudo apt install unzip -y
          pwd
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update -i /usr/local/aws-cli -b /usr/local/bin
          ls -al
          aws configure set default.region us-east-1
          aws configure set aws_access_key_id ${{ secrets.USER_AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.USER_AWS_SECRET_KEY }}

    - name: Copy atrtifacts to s3
      run: |
        ls -al
        cd ~/
        mkdir codedeploy_artifacts
        cd ~/codedeploy_artifacts
        ls -al
        cp -r /home/runner/work/webapp/webapp ~/codedeploy_artifacts
        pwd
        ls -al
        zip -r ~/codedeploy_artifacts.zip  ~/codedeploy_artifacts
        aws s3 cp ~/codedeploy_artifacts.zip s3://codedeploy.api --sse

    - name: Deploy code
      run: |
        pwd 
        cd ~/
        aws deploy create-deployment \
        --application-name csye6225-webapp \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --deployment-group-name csye6225-webapp-deployment \
        --description "My webapp" \
        --s3-location bucket=codedeploy.api,bundleType=zip,key=codedeploy_artifacts.zip
        
