name: Unit Tests

on: 
  pull_request: 
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
          node-version: '14.x'

    - name: build 
      run: |
            ls
            npm install

    - name: test
      run: |
          npm install pm2 -g
          pm2 start --name testServer npm -- test
          pm2 stop testServer